name: Build master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm i
    - run: npm run postinstall
    - run: npm run buildAndPack --if-present
    # - name: Archive artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: server-manager
    #     path: build